baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'My New Hugo Site'

theme = "univ"

defaultContentLanguage = "ja"
defaultContentLanguageInSubdir = true

[languages]

  [languages.ja]
    languageName = "日本語"
    weight = 1

  [languages.en]
    languageName = "English"
    weight = 2

[languages.ja.menu]
    [[languages.ja.menu.main]]
      name = "ホーム"
      url = "/"
      weight = 1
    [[languages.ja.menu.main]]
      name = "会社概要"
      url = "/about/"
      weight = 2
    [[languages.ja.menu.main]]
      name = "サービス"
      url = "/services/"
      weight = 3
    [[languages.ja.menu.main]]
      name = "ポートフォリオ"
      url = "/portfolio/"
      weight = 4
    [[languages.ja.menu.main]]
      name = "お問い合わせ"
      url = "/contact/"
      weight = 5


[languages.en.menu]
  [[languages.en.menu.main]]
      name = "Home"
      url = "/"
      weight = 1
    [[languages.en.menu.main]]
      name = "About"
      url = "/about/"
      weight = 2
    [[languages.en.menu.main]]
      name = "Services"
      url = "/services/"
      weight = 3
    [[languages.en.menu.main]]
      name = "Portfolio"
      url = "/portfolio/"
      weight = 4
    [[languages.en.menu.main]]
      name = "Contact"
      url = "/contact/"
      weight = 5